### ISSUE TITLE
"Abstract" and "BIB" buttons (in Publications) do NOT work, if the BibTeX entry key contains a column

### ISSUE THREAD

**Issue by mgiugliano** [sbryngelson/bryngelson_personal_template#10]
If (e.g.) the sample entry in ref.bib is changed from

`@article{feynman1939forces,`

to

`@article{feynman:1939forces,`

then the "Abstract" and "BIB" buttons (in Publications) do not work for that entry.
It is relevant as that style is often default (e.g.) by BiBDesk and other software to handle .bib files.

P.S. Thanks for this terrific template!!!!!!!!!!!!!!!!!!!!!!!!!!

P.P.S. In the README.md, it is written than ref.bin is in /cv. Instead it should go in /assets/ (according to the current _config.yml data provided).

**Comment by sbryngelson** [comment]
@mgiugliano You're welcome! 

For your question, I am actually unable to replicate your problem. Specifically, I changed a few of my `ref.bib` article entries to use the colon in the identifier but they both showed up with the `Abstract` and `BIB` buttons. I tested this using my website here https://github.com/comp-physics/comp-physics.github.io, though I'm pretty sure there aren't meaningful changes to this part of the code.

Regarding the `readme` -- good find, I will take care of this!
