### ISSUE TITLE
Unable to deploy successfully, github pages does not support jekyll scholar plugin.

### ISSUE THREAD

**Issue by wangyb97** [sbryngelson/bryngelson_personal_template#15]
Thank you so much for this beautiful template! I have my site all set up (based somewhat off of your group's site and it runs locally just fine, but the GH Pages deployment is breaking because it doesn't recognize the bibliography command, which is because jekyll-scholar isn't in GitHub's supported plugins. I tried a bunch of solutions to this that I found in a number of places, but haven't quite gotten it working (the closest attempt did publish the site, but seemed to just be "raw" HTML (without css).

I'm really not an expert in this stuff. Can you tell me in detail how to deploy this blog on github pages? 
Thanks a million!

**Comment by sbryngelson** [comment]
Did you follow the directions? You need to use `rake` and have `master` and `source` branches.

**Comment by wangyb97** [comment]
Thanks for the reply, I have redone a template repository following your instructions. However, my site is still not rendering the CSS. Can you help me check where the error is? My repository: https://github.com/wangyb97/aibio-lab. My website: https://wangyb97.github.io/aibio-lab/

**Comment by sbryngelson** [comment]
Unfortunately I do not have the time to do tech support. Fortunately Jekyll is very popular and this website template does not involve anything out of the ordinary. Closing as I cannot troubleshoot the issue.
