### ISSUE TITLE
GitHub pages build fails

### ISSUE THREAD

**Issue by lucasSaavedra123** [sbryngelson/bryngelson_personal_template#21]
Hi! For some reason, my template does not finish a build. However, the website can be visualized https://lucassaavedra123.github.io/. How can I solve it? Thank you!

**Comment by sbryngelson** [comment]
Not enough information in this issue to attempt to resolve.

**Comment by lucasSaavedra123** [comment]
In the [build](https://github.com/lucasSaavedra123/lucasSaavedra123.github.io/actions/runs/9831772733/job/27139625820), you can see the error. It's useless to repeat in the issue.

**Comment by sbryngelson** [comment]
issue is 

```
  Liquid Exception: Liquid syntax error (line 13): Unknown tag 'bibliography' in _pages/publications.md
```

**Comment by lucasSaavedra123** [comment]
Yes. How can I solve it? I do not see that other forked repositories have the same problem. Perhaps, It is something related with my GitHub configuration.

**Comment by sbryngelson** [comment]
I must admit I don't know. I don't have time to debug Jekyll issues. Perhaps consider posting on one of their GitHub repos/organizations or elsewhere. Thank you.

**Comment by lucasSaavedra123** [comment]
Thank you to you! Cheers, Lucas.
