### ISSUE TITLE
Works locally, but fails when on github: bibliography issue

### ISSUE THREAD

**Issue by JRD971000** [sbryngelson/bryngelson_personal_template#5]
Hi! Thank you very much for your beautiful template! I have just have an issue with the hosting part. Everything looks fine on my local machine, but when I push my commit to my repo, it gives the following error:

```   Liquid Exception: Liquid syntax error (line 13): Unknown tag 'bibliography' in _pages/publications.md ```

I also have the main branch, so it shouldn't be related to that I guess. Thanks a lot for your help!

**Comment by sbryngelson** [comment]
Are you sure you have the `rakefile` setup? When I look at your repo I think you don't, since you only have a `master` branch but not a `source` branch.

**Comment by JRD971000** [comment]
Thank you for getting back to me! Sorry if it's obvious, but I'm actually a bit confused. I did it all over again, and here is how I've done it: I forked the repo, cloned it, made the changes, and also modified the ```rakefile``` , then pushed it, but still the same error exists! I'd appreciate it if you could let me know what exactly I should do to get it right. Thanks a lot in advance!

**Comment by sbryngelson** [comment]
Did you run `$ rake publish` after you pushed it?

**Comment by JRD971000** [comment]
Thank you so much! It works and it builds cleanly! However, when I go to my website address (```JRD971000.github.io```) it automatically redirects me to ```http://your-website-name.com/```. I'm not sure if there is a problem on my end or if it's due to traffic on the GitHub servers.

**Comment by sbryngelson** [comment]
Ah, you just need to change the content of the `CNAME` file! https://github.com/sbryngelson/academic-website-template/blob/source/CNAME 

Change it to your github.io page.

**Comment by JRD971000** [comment]
I changed the ```CNAME``` to my address, but the issue still persists. I also wanted to check if the changes I made to the ```rakefile``` is legit:

```
system "git checkout -b source"
system "git remote add origin https://github.com/JRD971000/JRD971000.github.io.git"
system "git push origin source --force"
```

I just run the ```$ rake publish``` and it pushes the changes to the repo, and it builds successfully, but still redirects me to ```http://your-website-name.com/```.

**Comment by sbryngelson** [comment]
You may also need to go to your settings on the github repository and change what branch is being used to broadcast your site (it should be the master branch). Also, you can check out a "working" version of this template and compare your files to those: https://github.com/comp-physics/comp-physics.github.io 

The "source" branch will contain your rakefile and so on, and when you do `rake publish` it will force push to the master branch a compiled version of your website that github pages will deploy. 

Below is a screenshot of the settings for the github pages setup:

<img width="845" alt="Screenshot 2023-01-30 at 12 39 42" src="https://user-images.githubusercontent.com/39740593/215552529-c326f396-bae0-446b-b1cd-55f4bbdb2ad5.png">

**Comment by sbryngelson** [comment]
Update: Looking at your repo this is almost certainly what's going on. you should have a master and a source branch. The source branch will contain your rakefile and the jekyll source that is the core of your site, and the rakefile when called (`rake publish`) will push a new master branch that will be used for github pages. Right now you only have one branch. 

You may also find some useful info. in this search: https://www.google.com/search?q=how+to+use+github+pages+plugins+rakefile+source+master+deploy

**Comment by JRD971000** [comment]
Thank you very much for your comprehensive answer. I made all the steps you mentioned, but at the very end, when I want to finally run ```rake publish``` to launch the website using the ```master``` branch, it gives the following error:

```
error: src refspec master does not match any
error: failed to push some refs to 'https://github.com/JRD971000/JRD971000.github.io'
```
I also have set up my github pages settings as you mentioned above.

Sorry for coming back and forth on this!

**Comment by sbryngelson** [comment]
https://github.com/JRD971000/JRD971000.github.io/blob/source/Rakefile

Please see your `rakefile` above. You will see that it's pointing to my GitHub account, not yours.

**Comment by JRD971000** [comment]
Ah, right. I was on the ```source``` branch, but I had the correct address on ```master```. I just corrected it on the source as well but still the same issue exists🤷‍♂️.

**Comment by sbryngelson** [comment]
I think something isn't right here still. When you call `rake publish` with the updated `rakefile`, what happens? it should overwrite your entire master branch, like what is seen [here](https://github.com/comp-physics/comp-physics.github.io).

Also, a quick Google search on your error reveals [this](https://www.freecodecamp.org/news/error-src-refspec-master-does-not-match-any-how-to-fix-in-git/#:~:text=What%20Does%20src%20refspec%20master%20does%20not%20match%20any%20Mean%20in%20Git%3F&text=This%20error%20can%20occur%20for,try%20to%20push%20for%20it.) amongst other things to try.

**Comment by JRD971000** [comment]
Okay here is what's going on. I do have ```source``` and  ```master``` branches both locally and in the github repo:

<img width="627" alt="Screenshot 2023-01-31 at 4 04 09 PM" src="https://user-images.githubusercontent.com/71892896/215915821-79ce2b71-bf35-4b01-a06a-f3344fdf6ddf.png">

I figured out in the ```Rakefile```, in line 28, when after we call ```system "git init"``` it just considers a new git and when I print the branches it just shows ```main``` as the only branch. So if I don't manually make ```master``` in the rake file it says:

```
error: src refspec master does not match any
error: failed to push some refs to 'https://github.com/JRD971000/JRD971000.github.io'
```

I also tried to force making the branch in the ```Rakefile``` by 

``` system "git branch master"
system "git checkout master"```

but still, after running ```rake publish```, it redirects me to ```http://your-website-name.com``` although the ```master branch has been created with ```rake publish``` and ```source``` is up-to-date

**Comment by sbryngelson** [comment]
you run the `Rakefile` from the source branch, not the master branch. then the rakefile creates your website HTML files and deploys them on the master branch automatically (each labeled with a timestamp on the commit). these files will look quite different than the source branch files. then these master branch files will be deployed via GH Pages

**Comment by JRD971000** [comment]
Thank you very much, and sorry it took a bit long to fix. It's finally working, and please feel free to add it to your list!

**Comment by sbryngelson** [comment]
Glad to hear!
