### ISSUE TITLE
Issue happened when Kramdown parses about.md

### ISSUE THREAD

**Issue by ruinianxu** [sbryngelson/bryngelson_personal_template#6]
Hi Spencer,

Thank you so much for providing such beautiful and convenient template. I got the following error while I ran `bundle exec jekyll serve`. Do you have any ideas about it? Thanks
```
Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_pages/about.md':
                    uninitialized constant Kramdown::Utils::OrderedHash
```

**Comment by sbryngelson** [comment]
No problem. I am not familiar with this error. Perhaps try Google? This is the first answer for [Jekyll::Converters::Markdown encountered an error while converting](https://talk.jekyllrb.com/t/kramdown-parser-error-after-upgrading-to-jekyll-4/3959)

**Comment by ruinianxu** [comment]
I will give it a try. Thanks for the quick reply.

**Comment by ruinianxu** [comment]
Thanks for the provided solution. It works. It is due to debian installed jekyll. After removing it and reinstall jekyll via gem, it is working.
