### ISSUE TITLE
Trying to change font and background colour

### ISSUE THREAD

**Issue by BrinthanK** [sbryngelson/bryngelson_personal_template#8]
Hello,

I'm attempting to modify the font and background colors, but they keep reverting back to the default colors automatically. Could you please suggest a solution to overcome this issue? Thank you in advance.

**Comment by sbryngelson** [comment]
Would you mind being a bit more specific?

**Comment by BrinthanK** [comment]
h1, h2, h3, h4, h5, h6,
.h1, .h2, .h3, .h4, .h5, .h6 {
  font-family: inherit;
  font-weight: 400;
  line-height: 1.1;
  color: #964103; }
  h1 small,
  h1 .small, h2 small,
  h2 .small, h3 small,
  h3 .small, h4 small,
  h4 .small, h5 small,
  h5 .small, h6 small,
  h6 .small,
  .h1 small,
  .h1 .small, .h2 small,
  .h2 .small, .h3 small,
  .h3 .small, .h4 small,
  .h4 .small, .h5 small,
  .h5 .small, .h6 small,
  .h6 .small {
    font-weight: normal;
    line-height: 1;
    color: #999999; }
    
Suppose I'm altering the font colour here, and it promptly updates on the local site. However, upon committing to GitHub, it reverts to the default color.

**Comment by sbryngelson** [comment]
Based on this information I am unsure what is causing your problem -- sorry.

**Comment by BrinthanK** [comment]
My apologies for the short answers. I am kindly sharing the repository that is containing my website. Would this be helpful?

Link to the repository: https://github.com/BrinthanK/brinthank.github.io

**Comment by sbryngelson** [comment]
You have no source branch. Perhaps this is the issue. Please read the instructions carefully!

**Comment by BrinthanK** [comment]
Thank you for pointing out the problem. Let me try it.

**Comment by BrinthanK** [comment]
Thank you for your support @sbryngelson. I was pushing _site/ folder as well. That's where my mistake was.
